// Ancient Polities of Bharatavarsha - Comprehensive Database

export const CATEGORIES = [
  {
    id: 'mahajanapadas',
    title: 'Mahajanapadas',
    subtitle: 'The 16 Great Realms of Ancient India (c. 600–345 BCE)',
    image: './assets/cat_mahajanapadas.jpg',
    description: 'Ancient fortified cities, centers of philosophical debate, flourishing trade routes, and early urban civilization across the Indo-Gangetic plain and central highlands.',
    count: 16
  },
  {
    id: 'kingdoms',
    title: 'Kingdoms',
    subtitle: 'Monarchies & Sovereign Regional Realms',
    image: './assets/cat_kingdoms.jpg',
    description: 'Independent monarchies ruled by dynasties featuring royal courts, cavalry, war elephants, temple spires, and rich maritime and agricultural prosperity.',
    count: 11
  },
  {
    id: 'republics',
    title: 'Republics & Confederacies',
    subtitle: 'Gana-Sanghas & Democratic Clan Assemblies',
    image: './assets/cat_republics.jpg',
    description: 'Non-monarchical polities governed by elected clan representatives, council assemblies (Santhagaras), and collective consensus rather than hereditary kingship.',
    count: 5
  },
  {
    id: 'empires',
    title: 'Empires',
    subtitle: 'Pan-Indian Imperial Sovereign Sovereignties',
    image: './assets/cat_empires.jpg',
    description: 'Vast, multi-regional imperial powers with formidable standing armies, sophisticated central administration, monumental architecture, and expansive trade networks.',
    count: 18
  }
];

export const POLITIES_DATA = [
  // MAHAJANAPADAS (16)
  {
    id: 'magadha',
    name: 'Magadha',
    category: 'mahajanapadas',
    founder: 'Bimbisara / Brihadratha lineage',
    dynasty: 'Haryanka, Shishunaga, Nanda, Maurya',
    timeline: 'c. 600 BCE – 322 BCE',
    capital: 'Rajagriha (Girivraja), later Pataliputra',
    polityType: 'Monarchy (Mahajanapada)',
    image: './assets/cat_mahajanapadas.jpg',
    summary: 'Magadha emerged as the supreme political power in ancient Bharatavarsha. Situated in rich alluvial Bihar with abundant iron ore deposits and strategic river routes, it pioneered imperial expansion under Bimbisara, Ajatashatru, and the Nanda dynasty.',
    rulers: ['Bimbisara', 'Ajatashatru', 'Mahapadma Nanda'],
    contributions: 'Development of siege engines (Rathamusala, Mahashilakantaka), patronage of Buddhism and Jainism, founding of Pataliputra.',
    monuments: 'Cyclopean Wall of Rajgir, Griddhakuta Peak, ancient Pataliputra fortifications.',
    mapRegion: 'Lower Gangetic Plain (Modern Bihar & Jharkhand)'
  },
  {
    id: 'kosala',
    name: 'Kosala',
    category: 'mahajanapadas',
    founder: 'Ikshvaku Dynasty (Traditional)',
    dynasty: 'Ikshvaku',
    timeline: 'c. 600 BCE – 470 BCE',
    capital: 'Shravasti (later Ayodhya and Saketa)',
    polityType: 'Monarchy (Mahajanapada)',
    image: './assets/cat_mahajanapadas.jpg',
    summary: 'Kosala was a formidable northern kingdom intimately linked to the Ramayana tradition and early Buddhism. Under King Prasenajit, a contemporary of Gautama Buddha, Kosala dominated the Oudh region before being absorbed into Magadha.',
    rulers: ['Prasenajit (Pasenadi)', 'Vidudabha', 'Dasharatha (Legendary)'],
    contributions: 'Major patronage of Vedic learning and Buddhist monastic institutions, flourishing silk and agricultural trade.',
    monuments: 'Jetavana Monastery at Shravasti, ancient stupas of Ayodhya.',
    mapRegion: 'Awadh Region (Modern Uttar Pradesh)'
  },
  {
    id: 'avanti',
    name: 'Avanti',
    category: 'mahajanapadas',
    founder: 'Haihaya Clan / Pradyota',
    dynasty: 'Pradyota Dynasty',
    timeline: 'c. 600 BCE – 400 BCE',
    capital: 'Ujjayini (North) & Mahishmati (South)',
    polityType: 'Monarchy (Mahajanapada)',
    image: './assets/cat_mahajanapadas.jpg',
    summary: 'Avanti controlled the lucrative southern trade routes (Dakshinapatha) in central India. King Pradyota, known as Chanda Pradyota for his martial fury, made Ujjain a premier center of medicine, astronomy, and commerce.',
    rulers: ['Chanda Pradyota', 'Palaka', 'Nandivardhana'],
    contributions: 'Key node on the Uttarapatha and Dakshinapatha trade crossroads; home to renowned scholars and iron metalworks.',
    monuments: 'Ancient Ujjayini fortifications, Mahakaleshwar sanctuary precinct.',
    mapRegion: 'Malwa Region (Modern Madhya Pradesh)'
  },
  {
    id: 'vatsa',
    name: 'Vatsa (Vamsa)',
    category: 'mahajanapadas',
    founder: 'Nicaksu (Paurava lineage)',
    dynasty: 'Paurava Dynasty',
    timeline: 'c. 600 BCE – 450 BCE',
    capital: 'Kaushambi',
    polityType: 'Monarchy (Mahajanapada)',
    image: './assets/cat_mahajanapadas.jpg',
    summary: 'Located at the fertile confluence of the Ganga and Yamuna rivers, Vatsa was ruled by King Udayana, celebrated in classical Indian literature for his romantic legends, musical prowess on the veena, and diplomatic skill.',
    rulers: ['Udayana', 'Bodhi', 'Nicaksu'],
    contributions: 'Major center of cotton textile manufacture, fine arts, and Buddhist philosophy.',
    monuments: 'Ghoshitarama Monastery at Kaushambi, massive brick ramparts of Kaushambi.',
    mapRegion: 'Yamuna Valley (Modern Prayagraj region, UP)'
  },
  {
    id: 'gandhara',
    name: 'Gandhara',
    category: 'mahajanapadas',
    founder: 'Subala / Pushkarasarin',
    dynasty: 'Gandhara Lineage',
    timeline: 'c. 600 BCE – 518 BCE',
    capital: 'Takshashila (Taxila) and Pushkalavati',
    polityType: 'Monarchy (Mahajanapada)',
    image: './assets/cat_mahajanapadas.jpg',
    summary: 'Gandhara was the northwestern gateway of Bharatavarsha. Renowned for Takshashila, the world’s earliest pan-intellectual university, Gandhara synthesized Indian, Persian, and Hellenistic cultural and artistic influences.',
    rulers: ['Pushkarasarin', 'Subala'],
    contributions: 'Birthplace of Panini’s Sanskrit grammar, Greco-Buddhist Gandhara art style, Takshashila University.',
    monuments: 'Dharmarajika Stupa, Sirkap city ruins, Jaulian Monastery.',
    mapRegion: 'Peshawar Valley & Rawalpindi (Modern Khyber Pakhtunkhwa & Punjab)'
  },
  {
    id: 'kashi',
    name: 'Kashi',
    category: 'mahajanapadas',
    founder: 'Kasha / Divodasa',
    dynasty: 'Kashi Dynasty',
    timeline: 'c. 600 BCE – 480 BCE',
    capital: 'Varanasi',
    polityType: 'Monarchy (Mahajanapada)',
    image: './assets/cat_mahajanapadas.jpg',
    summary: 'Before its annexation by Kosala, Kashi was one of the wealthiest Mahajanapadas, world-famous for its high-grade cotton textiles, perfumery, ivory carving, and spiritual tradition along the sacred Ganga.',
    rulers: ['Brahmadatta', 'Divodasa', 'Ashvasena'],
    contributions: 'Spiritual foundation of Vedic, Jain (birthplace of Parshvanatha), and Buddhist learning.',
    monuments: 'Kashi riverbank ghats, Sarnath deer park precinct.',
    mapRegion: 'Varanasi Region (Modern Eastern Uttar Pradesh)'
  },
  {
    id: 'kuru',
    name: 'Kuru',
    category: 'mahajanapadas',
    founder: 'Kuru (Puru-Bharata Lineage)',
    dynasty: 'Kuru Dynasty',
    timeline: 'c. 600 BCE – 400 BCE',
    capital: 'Indraprastha & Hastinapura',
    polityType: 'Monarchy / Republic in later era',
    image: './assets/cat_mahajanapadas.jpg',
    summary: 'The Kuru realm was the birthplace of epic Mahabharata events and the codification of Vedic ritualism. Though shifting to a constitutional assembly in later centuries, Kuru retained high moral prestige.',
    rulers: ['Udayana of Kuru', 'Koravya'],
    contributions: 'Codification of Vedic hymns, development of early governance ethics (Rajadharma).',
    monuments: 'Hastinapura archaeological mounds, Purana Qila site (Indraprastha).',
    mapRegion: 'Delhi-Haryana & Western UP Region'
  },
  {
    id: 'panchala',
    name: 'Panchala',
    category: 'mahajanapadas',
    founder: 'Panchala Clan (Puru Branch)',
    dynasty: 'Panchala Dynasty',
    timeline: 'c. 600 BCE – 350 BCE',
    capital: 'Ahichchhatra (Northern) & Kampilya (Southern)',
    polityType: 'Monarchy / Republic',
    image: './assets/cat_mahajanapadas.jpg',
    summary: 'Panchala was divided into Northern and Southern realms by the Ganga river. Celebrated for philosophical conferences at royal courts and advanced urban fortification in Ahichchhatra.',
    rulers: ['Pravahana Jaivali', 'Drupada (Traditional)'],
    contributions: 'Early Upanishadic philosophy, town planning, punch-marked coinage.',
    monuments: 'Ahichchhatra brick fortress walls and temple terraced mounds.',
    mapRegion: 'Rohilkhand Region (Modern Bareilly & Farrukhabad, UP)'
  },
  {
    id: 'anga',
    name: 'Anga',
    category: 'mahajanapadas',
    founder: 'Anga (Anava Lineage)',
    dynasty: 'Anga Dynasty',
    timeline: 'c. 600 BCE – 530 BCE',
    capital: 'Champa (Champapuri)',
    polityType: 'Monarchy (Mahajanapada)',
    image: './assets/cat_mahajanapadas.jpg',
    summary: 'Anga lay east of Magadha and was renowned as a maritime trading power. Its capital Champa was a major river port whose merchants voyaged to Southeast Asia (Suvarnabhumi).',
    rulers: ['Brahma Datta', 'Karna (Legendary)'],
    contributions: 'Early Indian ocean trade networks, shipbuilding, metallurgy.',
    monuments: 'Champapuri port mounds, ancient river piers along Ganga.',
    mapRegion: 'Bhagalpur & Munger (Eastern Bihar & Bengal border)'
  },
  {
    id: 'vajji',
    name: 'Vajji (Vrijji)',
    category: 'mahajanapadas',
    founder: 'Confederacy of 8 Clans',
    dynasty: 'Licchavi, Videha, Jnatrika, Ugra',
    timeline: 'c. 600 BCE – 468 BCE',
    capital: 'Vaishali',
    polityType: 'Confederacy / Gana-Sangha',
    image: './assets/cat_republics.png',
    summary: 'Vajji was a powerful confederacy of eight republican clans governed by an elected council of 7,707 Raja leaders. It stood as a bastion of ancient Indian democracy until its conflict with Ajatashatru.',
    rulers: ['Chetaka (Head of Licchavi Council)', 'Siddhartha (Jnatrika Chief)'],
    contributions: 'First constitutional republic in world history, birthplace of Lord Mahavira, frequented by Lord Buddha.',
    monuments: 'Relic Stupa of Vaishali, Ananda Stupa, Abhishek Pushkarani (coronation tank).',
    mapRegion: 'North Bihar (Muzaffarpur & Vaishali region)'
  },
  {
    id: 'malla',
    name: 'Malla',
    category: 'mahajanapadas',
    founder: 'Malla Clan',
    dynasty: 'Malla Republics',
    timeline: 'c. 600 BCE – 450 BCE',
    capital: 'Kushinagara & Pava',
    polityType: 'Republic (Gana-Sangha)',
    image: './assets/cat_republics.png',
    summary: 'The Mallas were famed for their martial valor and democratic council administration. Divided into two branches at Kusinara and Pava, Malla territory is sacred as the Mahaparinirvana site of Lord Buddha.',
    rulers: ['Council of Malla Elders'],
    contributions: 'Wrestling and martial arts traditions, sacred Buddhist and Jain pilgrimage heritage.',
    monuments: 'Parinirvana Temple at Kushinagar, Ramabhar Stupa.',
    mapRegion: 'Eastern UP (Deoria & Kushinagar district)'
  },
  {
    id: 'chedi',
    name: 'Chedi',
    category: 'mahajanapadas',
    founder: 'Chedi (Yadav Branch)',
    dynasty: 'Chedi Lineage',
    timeline: 'c. 600 BCE – 400 BCE',
    capital: 'Suktimati (Sotthivati)',
    polityType: 'Monarchy (Mahajanapada)',
    image: './assets/cat_mahajanapadas.jpg',
    summary: 'Chedi lay along the Ken River along trade paths connecting the Gangetic plains to Central India. Mentioned in the Rigveda and Mahabharata, it was known for lush forests, cattle wealth, and brave warriors.',
    rulers: ['Shishupala (Traditional)', 'Dhammaghosa'],
    contributions: 'Strategic junction for overland trade routes; early iron smelting and forestry exports.',
    monuments: 'Suktimati riverbank ruins near Banda.',
    mapRegion: 'Bundelkhand Region (MP & UP border)'
  },
  {
    id: 'matsya',
    name: 'Matsya',
    category: 'mahajanapadas',
    founder: 'Matsya (Yadava-Chedi Branch)',
    dynasty: 'Matsya Dynasty',
    timeline: 'c. 600 BCE – 350 BCE',
    capital: 'Viratanagara (Modern Bairat)',
    polityType: 'Monarchy (Mahajanapada)',
    image: './assets/cat_mahajanapadas.jpg',
    summary: 'Matsya was situated south of Kuru and west of Yamuna. Known in epic tradition as the refuge of the Pandavas during exile, it was renowned for its warrior ethos and cattle husbandry.',
    rulers: ['Virata'],
    contributions: 'Early Buddhist rock-cut monasteries and Ashokan rock edicts at Bairat.',
    monuments: 'Bairat circular Buddhist temple (Gol Temple) and Ashokan inscription site.',
    mapRegion: 'Jaipur, Alwar & Bharatpur (Eastern Rajasthan)'
  },
  {
    id: 'surasena',
    name: 'Surasena',
    category: 'mahajanapadas',
    founder: 'Surasena (Yadava Lineage)',
    dynasty: 'Yadava / Vrishni',
    timeline: 'c. 600 BCE – 350 BCE',
    capital: 'Mathura',
    polityType: 'Monarchy / Republic',
    image: './assets/cat_mahajanapadas.jpg',
    summary: 'Surasena was centered around Mathura along the Yamuna river. The homeland of the Vrishni and Yadava clans, it was intimately connected to Shri Krishna and became a monumental artistic hub.',
    rulers: ['Avantiputra', 'Ugrasena', 'Kamsa (Legendary)'],
    contributions: 'Mathura School of Art (first native Buddha and Tirthankara icons), Krishna tradition.',
    monuments: 'Mathura red sandstone sculptures, Katra Keshavdev mounds.',
    mapRegion: 'Braj Region (Mathura, UP)'
  },
  {
    id: 'kamboja',
    name: 'Kamboja',
    category: 'mahajanapadas',
    founder: 'Kamboja Tribe',
    dynasty: 'Kamboja Chieftainships',
    timeline: 'c. 600 BCE – 330 BCE',
    capital: 'Rajapura (Modern Rajouri)',
    polityType: 'Constitutional Assembly / Republic (Varta-Sastropajivin)',
    image: './assets/cat_mahajanapadas.jpg',
    summary: 'Kamboja lay in the rugged Pamir and Hindu Kush mountain valleys. Famed across Asia for its superior cavalry and horse breeding, Kamboja combined agrarian craft with martial self-defense.',
    rulers: ['Sudakshina', 'Chandravarman'],
    contributions: 'Breeding of elite warhorses, trade connections across Central Asia, specialized cavalry tactics.',
    monuments: 'Ancient mountain fortresses of Rajouri and Swat Valley.',
    mapRegion: 'Trans-Indus & Hindu Kush (J&K, Pamir, East Afghanistan)'
  },
  {
    id: 'assaka',
    name: 'Assaka (Ashmaka)',
    category: 'mahajanapadas',
    founder: 'Asmaka (Ikshvaku Lineage)',
    dynasty: 'Assaka Dynasty',
    timeline: 'c. 600 BCE – 400 BCE',
    capital: 'Potali (Podana / Modern Bodhan)',
    polityType: 'Monarchy (Mahajanapada)',
    image: './assets/cat_mahajanapadas.jpg',
    summary: 'Assaka was the only Mahajanapada situated south of the Vindhya range, along the Godavari River. It served as a crucial bridge introducing northern Vedic and urban traditions to the Deccan region.',
    rulers: ['Brahmadatta of Assaka', 'Arunaka'],
    contributions: 'Pioneered urban settlement and metallurgy in the Godavari basin.',
    monuments: 'Bodhan ancient fortress mounds, Nizamabad ancient temples.',
    mapRegion: 'Godavari Basin (Modern Telangana & Maharashtra border)'
  },

  // KINGDOMS (11)
  {
    id: 'kalinga-kingdom',
    name: 'Kalinga Kingdom',
    category: 'kingdoms',
    founder: 'Kalinga (Legendary / Eastern Ganga roots)',
    dynasty: 'Kalinga Lineage, Chedi / Mahameghavahana',
    timeline: 'c. 800 BCE – 261 BCE (absorbed by Maurya)',
    capital: 'Dantapura / Kalinganagara (Mukhalingam)',
    polityType: 'Sovereign Monarchy',
    image: './assets/cat_kingdoms.png',
    summary: 'Kalinga was a fiercely independent maritime kingdom along the eastern sea coast. Renowned for its invincible navy, elephant corps, and rich overseas trade with Sri Lanka, Java, and Bali, its resistance led to the historic Kalinga War.',
    rulers: ['Kharavela (Later Mahameghavahana)', 'Srutarayu'],
    contributions: 'Maritime empire, Bali Yatra trade legacy, Hathigumpha inscription heritage.',
    monuments: 'Udayagiri and Khandagiri Caves, Sisupalgarh fortified city ruins.',
    mapRegion: 'Coastal Odisha & Northern Andhra Pradesh'
  },
  {
    id: 'chera-kingdom',
    name: 'Chera Kingdom (Early)',
    category: 'kingdoms',
    founder: 'Uthiyan Cheralathan',
    dynasty: 'Early Chera Dynasty',
    timeline: 'c. 3rd Century BCE – 3rd Century CE',
    capital: 'Vanci (Karur / Kodungallur) & Muziris port',
    polityType: 'Monarchy (Sangam Realm)',
    image: './assets/cat_kingdoms.png',
    summary: 'The Early Chera Kingdom ruled over Malabar and Kongu Nadu. Controlling the international spice port of Muziris, Chera kings exported pepper, pearls, and spices to the Roman Empire while patronizing Sangam literature.',
    rulers: ['Uthiyan Cheralathan', 'Nedum Cheralathan', 'Senguttuvan'],
    contributions: 'Muziris Indo-Roman spice trade hub, patronage of Silappatikaram epic, maritime diplomacy.',
    monuments: 'Muziris (Pattanam archaeological site), Karur ancient mint ruins.',
    mapRegion: 'Kerala & Western Tamil Nadu'
  },
  {
    id: 'pandya-kingdom',
    name: 'Pandya Kingdom (Early)',
    category: 'kingdoms',
    founder: 'Korkai Lineage / Palyagasalai Mudukudumi',
    dynasty: 'Early Pandya Dynasty',
    timeline: 'c. 600 BCE – 3rd Century CE',
    capital: 'Madurai & Korkai (Pearl Port)',
    polityType: 'Monarchy (Sangam Realm)',
    image: './assets/cat_kingdoms.png',
    summary: 'The Pandyas were an ancient dynasty celebrated in Sanskrit epics, Greek accounts (Megasthenes), and Sangam poems. Governing from Madurai, they were renowned for pearl diving, Sangam academies, and maritime commerce.',
    rulers: ['Nedunjeliyan I', 'Nedunjeliyan II (Talaialanganathu)', 'Palyagasalai Mudukudumi'],
    contributions: 'Founding of the Tamil Sangam academies, pearl trade across the Indian Ocean.',
    monuments: 'Korkai ancient pearl port mounds, Madurai Meenakshi original temple precinct.',
    mapRegion: 'Southern Tamil Nadu (Madurai, Tirunelveli, Thoothukudi)'
  },
  {
    id: 'early-chola-kingdom',
    name: 'Early Chola Kingdom',
    category: 'kingdoms',
    founder: 'Kantamana / Ellalan',
    dynasty: 'Early Chola Dynasty',
    timeline: 'c. 3rd Century BCE – 3rd Century CE',
    capital: 'Uraiyur & Poompuhar (Kaveripattinam)',
    polityType: 'Monarchy (Sangam Realm)',
    image: './assets/cat_kingdoms.png',
    summary: 'The Early Cholas controlled the fertile Kaveri delta. Under King Karikala Chola, they constructed the Grand Anicut (Kallanai), defeated confederated armies at Venni, and developed Poompuhar into a world-class seaport.',
    rulers: ['Karikala Chola', 'Ellalan', 'Nalankilli'],
    contributions: 'Construction of Grand Anicut (world’s oldest operational water-diversion dam), Sangam patron.',
    monuments: 'Kallanai Dam (Grand Anicut), Poompuhar port remains.',
    mapRegion: 'Kaveri Delta (Thanjavur, Tiruchirappalli, Nagapattinam)'
  },
  {
    id: 'kashi-kingdom',
    name: 'Kashi Kingdom',
    category: 'kingdoms',
    founder: 'King Kasha',
    dynasty: 'Kashi Monarchy',
    timeline: 'c. 1000 BCE – 500 BCE',
    capital: 'Varanasi',
    polityType: 'Monarchy',
    image: './assets/cat_kingdoms.png',
    summary: 'Independent Kingdom of Kashi was famed for moral kings like Brahmadatta described in Jataka tales. Its economic strength and control of the central Ganga trade led to intense wars with Kosala.',
    rulers: ['Brahmadatta', 'Divodasa'],
    contributions: 'Pre-Buddhist spiritual literature, early silk weaving, philosophical discourses.',
    monuments: 'Ancient Varanasi waterfront, Rajghat excavation site.',
    mapRegion: 'Varanasi District (Uttar Pradesh)'
  },
  {
    id: 'kosala-kingdom',
    name: 'Kosala Kingdom (Post-Vedic)',
    category: 'kingdoms',
    founder: 'King Ikshvaku',
    dynasty: 'Suryavamsha (Solar Dynasty)',
    timeline: 'c. 1100 BCE – 470 BCE',
    capital: 'Ayodhya, later Shravasti',
    polityType: 'Monarchy',
    image: './assets/cat_kingdoms.png',
    summary: 'The ancient kingdom of Kosala formed a core pillar of Vedic civilization. Home to Ayodhya, it preserved the legendary heritage of the Solar dynasty before expanding to Shravasti.',
    rulers: ['Mandhatri', 'Raghu', 'Dasharatha', 'Rama', 'Prasenajit'],
    contributions: 'Vedic rituals, Ramayana heritage, early urban centers.',
    monuments: 'Ayodhya ancient mounds, Shravasti city wall remains.',
    mapRegion: 'Central & Eastern Uttar Pradesh'
  },
  {
    id: 'gandhara-kingdom',
    name: 'Gandhara Kingdom (Vedic/Epic)',
    category: 'kingdoms',
    founder: 'Nagnajit / Subala',
    dynasty: 'Gandhara Royalty',
    timeline: 'c. 1000 BCE – 520 BCE',
    capital: 'Taxila & Pushkalavati',
    polityType: 'Monarchy',
    image: './assets/cat_kingdoms.png',
    summary: 'The early Gandhara Kingdom linked the Indian heartland to Silk Road trade routes. Mentioned prominently in the Rigveda and Mahabharata, it maintained close royal alliances with Kuru and Panchala.',
    rulers: ['Nagnajit', 'Subala', 'Shakuni (Epic)'],
    contributions: 'Early trade in horses, woolens, and precious lapis lazuli; Vedic learning centers.',
    monuments: 'Pushkalavati (Bala Hisar mound, Charsadda), early Taxila layers.',
    mapRegion: 'Khyber Pakhtunkhwa & Potohar Plateau'
  },
  {
    id: 'kuru-kingdom',
    name: 'Kuru Kingdom (Vedic)',
    category: 'kingdoms',
    founder: 'King Kuru',
    dynasty: 'Puru-Bharata',
    timeline: 'c. 1200 BCE – 500 BCE',
    capital: 'Hastinapura & Indraprastha',
    polityType: 'Monarchy',
    image: './assets/cat_kingdoms.png',
    summary: 'The Vedic Kuru Kingdom transformed early Vedic tribal society into the first organized state structure of ancient India, codifying the Shrauta rituals and compiling Samhitas.',
    rulers: ['Parikshit', 'Janamejaya', 'Dhritarashtra (Epic)'],
    contributions: 'Codification of the Yajurveda and Atharvaveda, development of early Indian statecraft.',
    monuments: 'Hastinapura Painted Grey Ware mounds, Tilpat site.',
    mapRegion: 'Haryana, Delhi & Upper Doab (UP)'
  },
  {
    id: 'panchala-kingdom',
    name: 'Panchala Kingdom (Vedic)',
    category: 'kingdoms',
    founder: 'Five Clans (Pancha-Jana)',
    dynasty: 'Panchala Royalty',
    timeline: 'c. 1100 BCE – 400 BCE',
    capital: 'Kampilya & Ahichchhatra',
    polityType: 'Monarchy',
    image: './assets/cat_kingdoms.png',
    summary: 'Panchala was celebrated for royal philosophers like King Pravahana Jaivali who hosted intellectual debates recorded in the Chandogya and Brihadaranyaka Upanishads.',
    rulers: ['Pravahana Jaivali', 'Keshin Dalbhya'],
    contributions: 'Upanishadic philosophy, early metallurgy, agricultural advancement in Ganga-Yamuna Doab.',
    monuments: 'Kampil archaeological mounds, Ahichchhatra ramparts.',
    mapRegion: 'Central Uttar Pradesh (Bareilly, Badaun, Farrukhabad)'
  },
  {
    id: 'mewar-kingdom',
    name: 'Mewar Kingdom (Medapata)',
    category: 'kingdoms',
    founder: 'Bappa Rawal (Guhila Dynasty)',
    dynasty: 'Guhila / Sisodia Rajput',
    timeline: 'c. 728 CE – 1948 CE',
    capital: 'Nagda, Chittorgarh, later Udaipur',
    polityType: 'Monarchy',
    image: './assets/cat_kingdoms.png',
    summary: 'Mewar stood for over a millennium as an unyielding fortress of independence. Under leaders like Bappa Rawal, Maharana Kumbha, Maharana Sanga, and Maharana Pratap, Mewar resisted foreign invasions with fierce honor.',
    rulers: ['Bappa Rawal', 'Maharana Kumbha', 'Maharana Sanga', 'Maharana Pratap'],
    contributions: 'Chittorgarh & Kumbhalgarh fort architecture, Mewari miniature painting, Vijay Stambha tower.',
    monuments: 'Chittorgarh Fort (UNESCO), Kumbhalgarh Great Wall, City Palace Udaipur.',
    mapRegion: 'Mewar Region (Southern Rajasthan)'
  },
  {
    id: 'ahom-kingdom',
    name: 'Ahom Kingdom',
    category: 'kingdoms',
    founder: 'Chaolung Sukaphaa',
    dynasty: 'Ahom Dynasty',
    timeline: '1228 CE – 1826 CE',
    capital: 'Charaideo, Garhgaon, Rangpur, Jorhat',
    polityType: 'Sovereign Monarchy',
    image: './assets/cat_kingdoms.png',
    summary: 'The Ahom Kingdom ruled the Brahmaputra Valley of Assam for nearly 600 years. Renowned for defeating Mughal invasions 17 times (notably under general Lachit Borphukan at Saraighat), Ahoms created a thriving, resilient society.',
    rulers: ['Sukaphaa', 'Suhungmung', 'Pratap Singha', 'Gadadhar Singha', 'Rudra Singha'],
    contributions: 'Buranji historical chronicles, Paik labor-administration system, unique brick amphitheaters.',
    monuments: 'Rang Ghar pavilion, Talatal Ghar palace, Maidams of Charaideo (UNESCO).',
    mapRegion: 'Brahmaputra Valley (Assam & parts of Northeast India)'
  },

  // REPUBLICS & CONFEDERACIES (5)
  {
    id: 'vajji-confederacy',
    name: 'Vajji Confederacy',
    category: 'republics',
    founder: 'Eight Allied Clans (Licchavis, Videhas, Jnatrikas, etc.)',
    dynasty: 'Elected Council of 7,707 Rajas',
    timeline: 'c. 600 BCE – 468 BCE',
    capital: 'Vaishali',
    polityType: 'Confederated Gana-Sangha (Republic)',
    image: './assets/cat_republics.png',
    summary: 'The Vajji Confederacy was the most famous democratic alliance of ancient India. Governed by a supreme assembly in Vaishali, it featured public debates, voting procedures (Salaka), and equal legislative rights among clan leaders.',
    rulers: ['Chetaka', 'Executive Committee of 9 Gana-Mukhyas'],
    contributions: 'Pioneered democratic procedures, secret ballot voting (Salaka-grahapaka), host to Mahavira & Buddha.',
    monuments: 'Vaishali Coronation Tank, Ashokan Lion Pillar at Kolhua, Relic Stupa.',
    mapRegion: 'Vaishali & Muzaffarpur (North Bihar)'
  },
  {
    id: 'malla-republic',
    name: 'Malla Republic',
    category: 'republics',
    founder: 'Malla Kshatriya Clan',
    dynasty: 'Democratic Santhagara Council',
    timeline: 'c. 600 BCE – 450 BCE',
    capital: 'Kushinagara (Kusinara) & Pava',
    polityType: 'Autonomous Republic (Gana-Sangha)',
    image: './assets/cat_republics.png',
    summary: 'The Mallas operated a twin-republic structure based at Kushinagara and Pava. They conducted state affairs in democratic council halls and were celebrated for martial chivalry and spiritual patronage.',
    rulers: ['Malla Assembly Elders'],
    contributions: 'Preservation of Buddhist and Jain relics; ancient martial academies.',
    monuments: 'Mahaparinirvana Temple, Ramabhar Stupa, Pava excavation site.',
    mapRegion: 'Kushinagar & Deoria (Eastern UP)'
  },
  {
    id: 'shakya-republic',
    name: 'Shakya Republic',
    category: 'republics',
    founder: 'Shakya Clan',
    dynasty: 'Santhagara Republic Council',
    timeline: 'c. 600 BCE – 480 BCE',
    capital: 'Kapilavastu',
    polityType: 'Republic (Gana-Sangha)',
    image: './assets/cat_republics.png',
    summary: 'The Shakya Republic ruled the foothills of the Himalayas. Governed by an elected chief (Raja Shuddhodana), the Shakya clan produced Gautama Buddha (Siddhartha Shakya), who transformed world philosophy.',
    rulers: ['Shuddhodana', 'Bhadrika'],
    contributions: 'Birthplace of Lord Buddha, development of egalitarian social ethics.',
    monuments: 'Kapilavastu ruins (Tilaurakot / Piprahwa), Lumbini Pillar precinct.',
    mapRegion: 'Terai region (Lumbini, Nepal & Siddharthnagar, UP)'
  },
  {
    id: 'licchavi-republic',
    name: 'Licchavi Republic',
    category: 'republics',
    founder: 'Licchavi Clan',
    dynasty: 'Licchavi Gana',
    timeline: 'c. 600 BCE – 400 BCE (and later revived in Nepal)',
    capital: 'Vaishali (Later Kathmandu Valley)',
    polityType: 'Republic (Gana-Sangha)',
    image: './assets/cat_republics.png',
    summary: 'The Licchavis were the dominant clan of the Vajji alliance. Famed for their strict judicial code, vibrant civic life, and diplomatic power, their bloodline was proud enough that Chandragupta I featured Licchavi lineage on Gupta coinage.',
    rulers: ['King Chetaka', 'Manadeva (Nepal branch)'],
    contributions: 'Advanced legal judiciary (seven tribunals), urban sanitation, enduring coinage legacy.',
    monuments: 'Vaishali brick ramparts, Changu Narayan Temple (Kathmandu Licchavi inscription).',
    mapRegion: 'North Bihar & Kathmandu Valley (Nepal)'
  },
  {
    id: 'koliya-republic',
    name: 'Koliya Republic',
    category: 'republics',
    founder: 'Koliya Clan',
    dynasty: 'Koliya Assembly',
    timeline: 'c. 600 BCE – 480 BCE',
    capital: 'Ramagrama & Devadaha',
    polityType: 'Republic (Gana-Sangha)',
    image: './assets/cat_republics.png',
    summary: 'Neighbors and kin to the Shakyas, the Koliyas governed an autonomous republic along the Rohini River. They maintained a well-organized police force and shared river water management systems through peaceful arbitration.',
    rulers: ['Koliya Tribal Council'],
    contributions: 'Early river water sharing agreements, Ramagrama stupa containing intact Buddha relics.',
    monuments: 'Ramagrama Stupa mound (unopened relic stupa in Nepal Terai).',
    mapRegion: 'Rohini River Basin (UP-Nepal border)'
  },

  // EMPIRES (18)
  {
    id: 'nanda-empire',
    name: 'Nanda Empire',
    category: 'empires',
    founder: 'Mahapadma Nanda',
    dynasty: 'Nanda Dynasty',
    timeline: 'c. 345 BCE – 322 BCE',
    capital: 'Pataliputra',
    polityType: 'Imperial Empire',
    image: './assets/cat_empires.png',
    summary: 'Mahapadma Nanda unified northern India into its first centralized empire by defeating rival Kshatriya monarchies. The Nandas accumulated legendary wealth, maintained an army of 200,000 infantry and 3,000 elephants, and paved the path for Mauryan pan-Indian statecraft.',
    rulers: ['Mahapadma Nanda', 'Dhana Nanda'],
    contributions: 'First central taxation system, vast standing army, canal irrigation works in Kalinga.',
    monuments: 'Pataliputra canal works, early palisade fortifications.',
    mapRegion: 'Entire Gangetic Plain, Odisha, and Central India'
  },
  {
    id: 'maurya-empire',
    name: 'Maurya Empire',
    category: 'empires',
    founder: 'Chandragupta Maurya & Chanakya (Kautilya)',
    dynasty: 'Mauryan Dynasty',
    timeline: '322 BCE – 185 BCE',
    capital: 'Pataliputra',
    polityType: 'Pan-Indian Imperial Sovereign State',
    image: './assets/cat_empires.png',
    summary: 'Founded by Chandragupta Maurya with the guidance of Chanakya, the Maurya Empire became the first major power to unite almost the entire Indian subcontinent. Reaching its zenith under Emperor Ashoka, it spread Dhamma, built grand highways, and instituted model public administration.',
    rulers: ['Chandragupta Maurya', 'Bindusara', 'Ashoka the Great', 'Dasharatha Maurya'],
    contributions: 'Arthashastra statecraft, Ashokan Rock & Pillar Edicts, Grand Trunk Road prototype, Lion Capital emblem.',
    monuments: 'Sarnath Lion Capital, Sanchi Stupa, Barabar Rock-Cut Caves, Pataliputra 80-Pillared Hall.',
    mapRegion: 'Entire Subcontinent (Except extreme southern tip) & Afghanistan'
  },
  {
    id: 'shunga-empire',
    name: 'Shunga Empire',
    category: 'empires',
    founder: 'Pushyamitra Shunga',
    dynasty: 'Shunga Dynasty',
    timeline: '185 BCE – 73 BCE',
    capital: 'Pataliputra, later Vidisha',
    polityType: 'Imperial Empire',
    image: './assets/cat_empires.png',
    summary: 'Established after Pushyamitra Shunga overthrew the last Mauryan king, the Shunga Empire defended central and eastern India against Indo-Greek invasions while sparking a massive renaissance of Sanskrit literature and stone architecture.',
    rulers: ['Pushyamitra Shunga', 'Agnimitra', 'Vasumitra', 'Devabhuti'],
    contributions: 'Enclosure and stone gateways of Sanchi Stupa, Patanjali’s Mahabhasya, Heliodorus pillar at Vidisha.',
    monuments: 'Bharhut Stupa railings, Sanchi Gateway sculptures, Vidisha Garuda Pillar.',
    mapRegion: 'Northern, Central, and Eastern India'
  },
  {
    id: 'satavahana-empire',
    name: 'Satavahana Empire (Andhra Dynasty)',
    category: 'empires',
    founder: 'Simuka',
    dynasty: 'Satavahana Dynasty',
    timeline: 'c. 1st Century BCE – 220 CE',
    capital: 'Pratishthana (Paithan) & Amaravati (Dharanikota)',
    polityType: 'Imperial Maritime Power',
    image: './assets/cat_empires.png',
    summary: 'The Satavahanas dominated the Deccan plateau for over four centuries. They bridged northern and southern India, issued lead and silver coinage with bilingual legends, patronized Prakrit literature, and led extensive maritime trade with Rome.',
    rulers: ['Simuka', 'Satakarni I', 'Gautamiputra Satakarni', 'Vashishtiputra Pulumavi', 'Yajna Sri Satakarni'],
    contributions: 'Gatha Saptasati anthology, rock-cut cave temples of Western Ghats, Amaravati Stupa marble reliefs.',
    monuments: 'Karla Caves, Bhaja Caves, Amaravati Great Stupa, Nashik Cave Inscriptions.',
    mapRegion: 'Deccan Plateau (Maharashtra, Andhra Pradesh, Telangana, Karnataka)'
  },
  {
    id: 'kushan-empire',
    name: 'Kushan Empire',
    category: 'empires',
    founder: 'Kujula Kadphises',
    dynasty: 'Kushan Dynasty',
    timeline: 'c. 30 CE – 375 CE',
    capital: 'Purushapura (Peshawar) & Mathura',
    polityType: 'Trans-Eurasian Empire',
    image: './assets/cat_empires.png',
    summary: 'The Kushan Empire linked Northern India across the Silk Road to Central Asia and Rome. Under Emperor Kanishka the Great, it sponsored the Fourth Buddhist Council, popularized Mahayana Buddhism, and fostered Mathura & Gandhara art.',
    rulers: ['Kujula Kadphises', 'Vima Kadphises', 'Kanishka I (The Great)', 'Huvishka', 'Vasudeva I'],
    contributions: 'Gold coin minting standard, Silk Road trade mediation, Fourth Buddhist Council, Gandhara & Mathura art.',
    monuments: 'Kanishka Stupa at Peshawar, Mathura royal portrait statues, Takht-i-Bahi.',
    mapRegion: 'North India, Pakistan, Afghanistan, Tajikistan, Xinjiang'
  },
  {
    id: 'gupta-empire',
    name: 'Gupta Empire',
    category: 'empires',
    founder: 'Chandragupta I',
    dynasty: 'Gupta Dynasty',
    timeline: 'c. 319 CE – 550 CE',
    capital: 'Pataliputra & Ujjain',
    polityType: 'Pan-Indian Golden Age Empire',
    image: './assets/cat_empires.png',
    summary: 'The Gupta Empire ushered in the Classical Golden Age of India. Under Samudragupta and Chandragupta II (Vikramaditya), Bharatavarsha achieved unequaled heights in mathematics (Aryabhata), astronomy, Sanskrit literature (Kalidasa), and rust-resistant metallurgy.',
    rulers: ['Chandragupta I', 'Samudragupta', 'Chandragupta II (Vikramaditya)', 'Kumaragupta I', 'Skandagupta'],
    contributions: 'Zero & decimal place-value system, Iron Pillar of Delhi, Ajanta cave murals, Nalanda University founding.',
    monuments: 'Iron Pillar of Delhi, Ajanta Caves (Phase II), Deogarh Dashavatara Temple, Sarnath Standing Buddha.',
    mapRegion: 'Northern, Central, and Eastern Subcontinent'
  },
  {
    id: 'vakataka-empire',
    name: 'Vakataka Empire',
    category: 'empires',
    founder: 'Vindhyashakti',
    dynasty: 'Vakataka Dynasty',
    timeline: 'c. 250 CE – 500 CE',
    capital: 'Vatsagulma (Washim) & Nagardhan',
    polityType: 'Sovereign Imperial Power',
    image: './assets/cat_empires.png',
    summary: 'The Vakatakas ruled the Deccan core simultaneously with the Guptas in the north. Dynasty matriarch Prabhavatigupta (daughter of Chandragupta II) ruled as regent, patronizing high Sanskritic culture and the world-famous rock-cut murals of Ajanta.',
    rulers: ['Vindhyashakti', 'Pravarasena I', 'Prabhavatigupta (Regent)', 'Harishena'],
    contributions: 'Patronage of Ajanta Cave painting masterpieces, Sanskrit Kavya poetry, structural stone temples.',
    monuments: 'Ajanta Cave Murals (Caves 1, 2, 16, 17), Mansar brick temple complex.',
    mapRegion: 'Vidarbha & Deccan (Modern Maharashtra & MP)'
  },
  {
    id: 'harsha-empire',
    name: 'Harsha Empire (Vardhana Dynasty)',
    category: 'empires',
    founder: 'Harshavardhana',
    dynasty: 'Pushyabhuti / Vardhana Dynasty',
    timeline: '606 CE – 647 CE',
    capital: 'Kannauj (Kanyakubja)',
    polityType: 'Imperial Hegemony',
    image: './assets/cat_empires.png',
    summary: 'Emperor Harshavardhana united Northern India after the fall of the Guptas. A scholar-king who authored three Sanskrit plays, Harsha patronized Chinese pilgrim Xuanzang, held grand assemblies at Kannauj, and gave massive endowments to Nalanda University.',
    rulers: ['Prabhakaravardhana', 'Rajyavardhana', 'Harshavardhana'],
    contributions: 'Sanskrit plays (Nagananda, Ratnavali, Priyadarsika), patronage of Xuanzang, Kannauj assembly.',
    monuments: 'Kannauj imperial assembly site, expanded Nalanda Mahavihara structures.',
    mapRegion: 'Entire Northern India (Punjab to Bengal, Narmada river boundary)'
  },
  {
    id: 'chalukya-empire',
    name: 'Chalukya Empire (Badami)',
    category: 'empires',
    founder: 'Pulakeshin I',
    dynasty: 'Badami Chalukya Dynasty',
    timeline: '543 CE – 753 CE',
    capital: 'Vatapi (Badami)',
    polityType: 'Deccan Imperial Sovereign Power',
    image: './assets/cat_empires.png',
    summary: 'The Badami Chalukyas dominated the Deccan. Emperor Pulakeshin II famously defeated Harsha on the banks of the Narmada River. Their reign birthed the magnificent Vesara style of Indian temple architecture at Badami, Aihole, and Pattadakal.',
    rulers: ['Pulakeshin I', 'Kirtivarman I', 'Pulakeshin II', 'Vikramaditya I', 'Vikramaditya II'],
    contributions: 'Vesara temple architecture, Badami rock-cut rock cave temples, Aihole inscription.',
    monuments: 'Badami Cave Temples, Pattadakal Temple Complex (UNESCO), Durga Temple Aihole.',
    mapRegion: 'Deccan Plateau & Karnataka, Maharashtra, Telangana'
  },
  {
    id: 'pallava-empire',
    name: 'Pallava Empire',
    category: 'empires',
    founder: 'Simhavishnu',
    dynasty: 'Pallava Dynasty',
    timeline: '275 CE – 897 CE',
    capital: 'Kanchipuram',
    polityType: 'Imperial Coastal Realm',
    image: './assets/cat_empires.png',
    summary: 'The Pallavas transformed South Indian art, sea-trade, and temple building. Under Narasimhavarman I (Mamalla), they created the monolithic rock-cut Rathas of Mamallapuram and sent naval expeditions to Sri Lanka, establishing cultural routes to Southeast Asia.',
    rulers: ['Simhavishnu', 'Mahendravarman I', 'Narasimhavarman I (Mamalla)', 'Narasimhavarman II (Rajasimha)'],
    contributions: 'Monolithic rock-cut temples, Shore Temple, Grantha script (ancestor to Southeast Asian scripts).',
    monuments: 'Mamallapuram Pancha Rathas & Shore Temple (UNESCO), Kailasanathar Temple Kanchipuram.',
    mapRegion: 'Tondaimandalam (Northern Tamil Nadu & Southern AP)'
  },
  {
    id: 'rashtrakuta-empire',
    name: 'Rashtrakuta Empire',
    category: 'empires',
    founder: 'Dantidurga',
    dynasty: 'Rashtrakuta Dynasty',
    timeline: '753 CE – 982 CE',
    capital: 'Manyakheta (Malkhed)',
    polityType: 'Pan-Indian Imperial Sovereign State',
    image: './assets/cat_empires.png',
    summary: 'Arab geographers ranked the Rashtrakuta Empire as one of the four great empires of the world alongside China, Baghdad, and Constantinople. Under Amoghavarsha I and Krishna III, they dominated North and South India, carving the colossal Kailasa Temple at Ellora.',
    rulers: ['Dantidurga', 'Krishna I', 'Govinda III', 'Amoghavarsha I', 'Krishna III'],
    contributions: 'Kailasa Temple at Ellora (world’s largest monolithic rock-cut monument), Kavirajamarga (earliest Kannada work).',
    monuments: 'Kailasa Temple Ellora (Cave 16), Elephanta Caves, Malkhed Fort.',
    mapRegion: 'Deccan, Central India, and parts of North and South India'
  },
  {
    id: 'gurjara-pratihara-empire',
    name: 'Gurjara-Pratihara Empire',
    category: 'empires',
    founder: 'Nagabhata I',
    dynasty: 'Gurjara-Pratihara Dynasty',
    timeline: 'mid-8th Century CE – 1036 CE',
    capital: 'Kannauj',
    polityType: 'Imperial Sovereign Power',
    image: './assets/cat_empires.png',
    summary: 'The Gurjara-Pratiharas formed an impregnable bulwark defending Northern India against Caliphate invasions from Sindh. Under Mihira Bhoja, the empire stretched from the foothills of the Himalayas to the Narmada.',
    rulers: ['Nagabhata I', 'Vatsaraja', 'Nagabhata II', 'Mihira Bhoja', 'Mahendrapala I'],
    contributions: 'Pratihara style temple architecture, defense of Indian frontier, patronage of poet Rajasekhara.',
    monuments: 'Bateshwar Temple Complex, Teli ka Mandir Gwalior, Khajuraho early shrines.',
    mapRegion: 'Northern & Western India (Rajasthan, MP, UP, Gujarat)'
  },
  {
    id: 'pala-empire',
    name: 'Pala Empire',
    category: 'empires',
    founder: 'Gopala I (Elected by democratic consensus)',
    dynasty: 'Pala Dynasty',
    timeline: '750 CE – 1161 CE',
    capital: 'Gaur, Bikrampur, Pataliputra',
    polityType: 'Imperial Buddhist Power',
    image: './assets/cat_empires.png',
    summary: 'The Pala Empire was founded when Gopala was democratically elected by regional chieftains to end anarchy (Matsyanyaya). Pala kings patronized Mahayana/Vajrayana Buddhism, founding Vikramashila and Somapura universities and spreading art to Tibet & Southeast Asia.',
    rulers: ['Gopala I', 'Dharmapala', 'Devapala', 'Mahipala I', 'Ramapala'],
    contributions: 'Founding of Vikramashila & Somapura universities, Pala palm-leaf bronze sculpture school, Tibetan Buddhist links.',
    monuments: 'Somapura Mahavihara (UNESCO), Vikramashila ruins, Odantapuri site.',
    mapRegion: 'Bengal & Bihar (Modern Bangladesh, West Bengal, Bihar)'
  },
  {
    id: 'chola-empire',
    name: 'Chola Empire (Imperial)',
    category: 'empires',
    founder: 'Vijayalaya Chola',
    dynasty: 'Imperial Chola Dynasty',
    timeline: '848 CE – 1279 CE',
    capital: 'Thanjavur & Gangaikonda Cholapuram',
    polityType: 'Thalassocratic Maritime Empire',
    image: './assets/cat_empires.png',
    summary: 'The Imperial Cholas established a legendary thalassocratic maritime empire across the Bay of Bengal. Under Rajaraja I and Rajendra I, their grand navy conquered Sri Lanka, Srivijaya (Sumatra/Malaysia), built the Brihadisvara Temple, and perfected bronze casting.',
    rulers: ['Vijayalaya', 'Aditya I', 'Parantaka I', 'Rajaraja Chola I', 'Rajendra Chola I', 'Kulothunga I'],
    contributions: 'Chola bronzes (Natasharaja icon), Brihadisvara Temple engineering, autonomous village assemblies (Kudavolai democracy system).',
    monuments: 'Brihadisvara Temple Thanjavur (UNESCO), Gangaikonda Cholapuram, Airavatesvara Temple Darasuram.',
    mapRegion: 'South India, Sri Lanka, Maldives, parts of Malaysia, Indonesia & Myanmar coastal nodes'
  },
  {
    id: 'hoysala-empire',
    name: 'Hoysala Empire',
    category: 'empires',
    founder: 'Nripa Kama II / Sala',
    dynasty: 'Hoysala Dynasty',
    timeline: '1026 CE – 1343 CE',
    capital: 'Belur, later Halebidu (Dorasamudra)',
    polityType: 'Imperial Power',
    image: './assets/cat_empires.png',
    summary: 'The Hoysalas ruled Karnataka and parts of Tamil Nadu. Renowned for their star-shaped chloritic schist (soapstone) temples with exquisite, high-precision carved friezes, Hoysala rulers were patrons of Kannada and Sanskrit literature.',
    rulers: ['Vishnuvardhana', 'Veera Ballala II', 'Veera Ballala III'],
    contributions: 'Hoysala architecture (star-shaped platforms, intricate soapstone carvings), Kannada literary patron.',
    monuments: 'Hoysaleswara Temple Halebidu (UNESCO), Chennakesava Temple Belur, Keshava Temple Somanathapura.',
    mapRegion: 'Karnataka & Western Tamil Nadu'
  },
  {
    id: 'kakatiya-empire',
    name: 'Kakatiya Empire',
    category: 'empires',
    founder: 'Prola I / Beta I',
    dynasty: 'Kakatiya Dynasty',
    timeline: '1163 CE – 1323 CE',
    capital: 'Orugallu (Warangal)',
    polityType: 'Imperial Sovereign Power',
    image: './assets/cat_empires.png',
    summary: 'The Kakatiyas ruled Telangana and Andhra Pradesh. Famous for Rani Rudrama Devi—one of the few reigning queens of Indian history—and King Prataparudra, the Kakatiyas built massive irrigation tanks, stone fortresses, and the earthquake-resistant Ramappa Temple.',
    rulers: ['Prola II', 'Rudra Deva', 'Ganapati Deva', 'Rani Rudrama Devi', 'Prataparudra II'],
    contributions: 'Chain-tank irrigation engineering, Warangal Kirti Toranas (arches), Ramappa sandbox foundation system.',
    monuments: 'Ramappa Temple (UNESCO), Warangal Fort & Gateway Arches, Thousand Pillar Temple Hanamkonda.',
    mapRegion: 'Telangana & Andhra Pradesh'
  },
  {
    id: 'vijayanagara-empire',
    name: 'Vijayanagara Empire (Karnata Empire)',
    category: 'empires',
    founder: 'Harihara I & Bukka Raya I (Sangama Brothers)',
    dynasty: 'Sangama, Saluva, Tuluva, Aravidu',
    timeline: '1336 CE – 1646 CE',
    capital: 'Vijayanagara (Hampi)',
    polityType: 'Imperial Sovereign Realm',
    image: './assets/cat_empires.png',
    summary: 'Founded to safeguard Southern Indian culture and sovereignty, Vijayanagara became one of the wealthiest global metropolis of the medieval world. Reaching its zenith under Emperor Krishnadevaraya, it sponsored poetry, international trade, and grand granite architecture.',
    rulers: ['Harihara I', 'Bukka Raya I', 'Deva Raya II', 'Krishnadevaraya', 'Achyuta Deva Raya', 'Rama Raya'],
    contributions: 'Rayagopuram temple towers, Stone Chariot engineering, Amuktamalyada literature, global diamond trade.',
    monuments: 'Virupaksha Temple, Stone Chariot at Vittala Temple, Lotus Mahal, Elephant Stables Hampi (UNESCO).',
    mapRegion: 'Entire South India (Karnataka, Andhra, Telangana, Tamil Nadu, Kerala)'
  },
  {
    id: 'maratha-empire',
    name: 'Maratha Empire & Confederacy',
    category: 'empires',
    founder: 'Chhatrapati Shivaji Maharaj',
    dynasty: 'Bhonsle Chhatrapatis & Peshwa Administration',
    timeline: '1674 CE – 1818 CE',
    capital: 'Raigad, Jinji, Satara, Pune',
    polityType: 'Sovereign Swarajya / Imperial Confederation',
    image: './assets/cat_empires.png',
    summary: 'Founded by Chhatrapati Shivaji Maharaj on the principles of Hindavi Swarajya, the Marathas established a formidable naval, hill-fortress, and cavalry army. Expanding across India under Peshwa Baji Rao I, the Maratha Empire dominated 18th-century Bharatavarsha.',
    rulers: ['Chhatrapati Shivaji Maharaj', 'Chhatrapati Sambhaji Maharaj', 'Peshwa Baji Rao I', 'Peshwa Balaji Baji Rao', 'Mahadaji Shinde'],
    contributions: 'Ashta Pradhan cabinet council, Ganimi Kava (guerrilla warfare), Maratha sea forts & navy, Swarajya governance.',
    monuments: 'Raigad Fort, Sindhudurg Sea Fort, Shanivar Wada Pune, Pratapgad Fort.',
    mapRegion: 'Pan-Indian (Maharashtra, MP, Gujarat, Rajasthan, Punjab to Odisha & Tamil Nadu)'
  }
];

export const GREAT_RULERS = [
  {
    id: 'chandragupta-maurya',
    name: 'Chandragupta Maurya',
    title: 'Founder of the Maurya Empire',
    dynasty: 'Maurya Dynasty',
    reign: 'c. 322 BCE – 297 BCE',
    image: './assets/cat_empires.png',
    achievements: 'Overthrew the Nanda dynasty, defeated Seleucus I Nicator to secure India’s northwestern frontier, unified Northern and Central India, and established the centralized administrative apparatus detailed in Chanakya’s Arthashastra.'
  },
  {
    id: 'ashoka-the-great',
    name: 'Emperor Ashoka',
    title: 'Chakravartin Samrat (Ashoka the Great)',
    dynasty: 'Maurya Dynasty',
    reign: 'c. 268 BCE – 232 BCE',
    image: './assets/cat_empires.png',
    achievements: 'Expanded the empire to its maximum extent. Following the Kalinga War, he embraced Dhamma, carved moral edicts across rocks and pillars from Afghanistan to Karnataka, dispatched diplomatic missions to Europe & Asia, and built 84,000 stupas.'
  },
  {
    id: 'samudragupta',
    name: 'Samudragupta',
    title: 'Napoleon of India / Kaviraja',
    dynasty: 'Gupta Dynasty',
    reign: 'c. 335 CE – 375 CE',
    image: './assets/cat_empires.png',
    achievements: 'Brilliant military commander recorded in the Prayag Prashasti pillar inscription. Subjugated 9 northern kings and 12 southern kings, performed the Ashvamedha sacrifice, minted exquisite gold coins, and was an accomplished veena player and poet.'
  },
  {
    id: 'harshavardhana',
    name: 'Emperor Harshavardhana',
    title: 'Maharajadhiraja of Kannauj',
    dynasty: 'Vardhana Dynasty',
    reign: '606 CE – 647 CE',
    image: './assets/cat_empires.png',
    achievements: 'Reunified Northern India after post-Gupta fragmentations, patronized Xuanzang, established Kannauj as an imperial cultural capital, endowed Nalanda University, and authored Sanskrit masterpieces Ratnavali and Nagananda.'
  },
  {
    id: 'rajaraja-chola-i',
    name: 'Rajaraja Chola I',
    title: 'Rajaraja the Great / Arulmozhi Varman',
    dynasty: 'Chola Dynasty',
    reign: '985 CE – 1014 CE',
    image: './assets/cat_kingdoms.png',
    achievements: 'Built the monumental granite Brihadisvara Temple at Thanjavur, established the naval conquest of Sri Lanka and Maldives, introduced detailed revenue survey and audit systems, and perfected democratic Kudavolai village governance.'
  },
  {
    id: 'rajendra-chola-i',
    name: 'Rajendra Chola I',
    title: 'Gangaikonda Cholan / Victor of the Ganga & Seas',
    dynasty: 'Chola Dynasty',
    reign: '1014 CE – 1044 CE',
    image: './assets/cat_kingdoms.png',
    achievements: 'Led the legendary northern campaign to the Ganga river, founded Gangaikonda Cholapuram, launched a successful overseas naval expedition against the Srivijaya Empire in Sumatra and Malaysia, securing Indian Ocean trade routes.'
  },
  {
    id: 'krishnadevaraya',
    name: 'Emperor Krishnadevaraya',
    title: 'Kannada Rajya Rama Ramana / Andhra Bhoja',
    dynasty: 'Tuluva Dynasty (Vijayanagara)',
    reign: '1509 CE – 1529 CE',
    image: './assets/cat_empires.png',
    achievements: 'Led Vijayanagara to its peak of military and architectural glory, defeated the Deccan Sultanates and Gajapatis, patronized Ashtadiggajas (8 great Telugu poets), authored Amuktamalyada, and built Hampi’s iconic stone chariot and temples.'
  },
  {
    id: 'shivaji-maharaj',
    name: 'Chhatrapati Shivaji Maharaj',
    title: 'Shakakarta / Founder of Maratha Swarajya',
    dynasty: 'Bhonsle Dynasty',
    reign: '1674 CE – 1680 CE',
    image: './assets/cat_empires.png',
    achievements: 'Pioneered Hindavi Swarajya, developed naval sea power along the Konkan coast, mastered Ganimi Kava (guerrilla warfare), constructed over 300 hill and sea forts, instituted the Ashta Pradhan cabinet council, and revived indigenous statecraft.'
  }
];

export const TIMELINE_EVENTS = [
  {
    id: 'vedic-age',
    title: 'Vedic Age & Clan Assemblies',
    period: 'c. 1500 BCE – 600 BCE',
    category: 'Foundational Era',
    description: 'Codification of Vedic texts, transition from pastoral tribal assemblies (Sabha and Samiti) to settled territorial janapadas across Northern India.',
    significance: 'Laid the cultural, philosophical, and social foundations of Indian statecraft and Rajadharma ethics.'
  },
  {
    id: 'mahajanapada-era',
    title: 'Rise of Mahajanapadas & Gana-Sanghas',
    period: 'c. 600 BCE – 345 BCE',
    category: 'Mahajanapadas & Republics',
    description: 'Emergence of 16 great realms and democratic republics (Vaishali, Shakya, Malla). Intellectual revolution of Upanishads, Jainism, and Buddhism.',
    significance: 'First urban revolution, introduction of punch-marked coinage, world’s earliest democratic republics.'
  },
  {
    id: 'nanda-period',
    title: 'Nanda Empire Consolidation',
    period: 'c. 345 BCE – 322 BCE',
    category: 'Empires',
    description: 'Mahapadma Nanda centralizes power at Pataliputra, building an army of 200,000 soldiers and establishing imperial tax systems.',
    significance: 'Precursor to pan-Indian empire building, ending feudal regional hegemony.'
  },
  {
    id: 'maurya-era',
    title: 'Mauryan Pan-Indian Empire',
    period: '322 BCE – 185 BCE',
    category: 'Empires',
    description: 'Chandragupta Maurya and Chanakya build India’s first unified empire. Emperor Ashoka propagates Dhamma and builds rock/pillar edicts.',
    significance: 'Political unification of almost the entire subcontinent, Arthashastra administration, international diplomatic missions.'
  },
  {
    id: 'gupta-golden-age',
    title: 'Gupta Empire Golden Age',
    period: 'c. 319 CE – 550 CE',
    category: 'Empires',
    description: 'Chandragupta II Vikramaditya and Samudragupta oversee unmatched advances in mathematics (Aryabhata), Sanskrit literature, metalworking, and cave art.',
    significance: 'Classical Renaissance of Bharatavarsha, invention of zero/decimal system, Nalanda University flourishing.'
  },
  {
    id: 'early-medieval-realms',
    title: 'Early Medieval Deccan & Southern Hegemonies',
    period: 'c. 550 CE – 1200 CE',
    category: 'Kingdoms & Empires',
    description: 'Badami Chalukyas, Pallavas, Rashtrakutas, and Gurjara-Pratiharas compete for imperial supremacy. Construction of Ellora Kailasa temple and Mamallapuram.',
    significance: 'Peak of structural temple architecture, maritime trade expansion, defeat of early invasions.'
  },
  {
    id: 'chola-maritime-supremacy',
    title: 'Imperial Chola Maritime Expansion',
    period: '848 CE – 1279 CE',
    category: 'Empires',
    description: 'Rajaraja I and Rajendra I build a thalassocratic navy, conquering Sri Lanka and Srivijaya (Sumatra/Malaysia), building Brihadisvara Temple.',
    significance: 'Dominance of Indian Ocean sea trade, Chola bronze artistry, democratic Kudavolai council governance.'
  },
  {
    id: 'vijayanagara-era',
    title: 'Vijayanagara Empire (Karnata Realm)',
    period: '1336 CE – 1646 CE',
    category: 'Empires',
    description: 'Founded at Hampi by Harihara & Bukka. Reaches global prominence under Krishnadevaraya, preserving South Indian art, temples, and literature.',
    significance: 'Cultural sanctuary of South India, international trade hub for horse, silk, and diamond merchants.'
  },
  {
    id: 'maratha-swarajya',
    title: 'Maratha Swarajya & Confederation',
    period: '1674 CE – 1818 CE',
    category: 'Empires',
    description: 'Chhatrapati Shivaji Maharaj establishes Hindavi Swarajya. Peshwa Baji Rao I expands Maratha power across the subcontinent from Attock to Cuttack.',
    significance: 'Resurgence of native Indian sovereignty, guerrilla tactics (Ganimi Kava), creation of Maratha naval fleet.'
  }
];
